# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e10bfa6b9bad3c421ecfb456ff3690db2e9ed9fe2f93f895fef97b82b8c46673a8fa6747f129afd60d3a63e231ee4be5437f881e8b442b0f50a8ca9fc5b863f9

test:
  secret_key_base: ed16401378775cd496bc83f03115ed95a69e50c9d29338207fa9390aa229633318e7749b4331339c34eb27fc52cea90e759cb61697877c56df005a49d6646bae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
